### ISSUE TITLE
Just a suggestion for README

### ISSUE THREAD

**Issue by FishInWave** [westonrobot/wrp_sdk#1]
When I catkin_make the package for first time, an error occurs as :
`couldn't not find a package configuration file provided by "webots_ros" with any of the following names:
webots_rosConfig.cmake
webots_ros-config.cmake
`
So I run `sudo apt-get install ros-kinetic-webots-ros`, and then catkin_make finished successfully.
I think it's better to remind user of dependency package.

**Comment by rdu-weston** [comment]
Thanks for your feedback. I will update the document accordingly soon.
